### PR TITLE
Add GH links

### LINKED ISSUE #9: [Feature Request] Add GitHub link to credential modal & dashboard
### Describe the feature you'd like to request

Can we add a GitHub link/button both to the Credentials modal & somewhere on the dashboard?

In the Credentials modal there should be a button to get to the GitHub repo, but also an area some text to send people to the README. Right now, if you land on the page & you don't already know what you're doing, you get stuck in this modal being asked for a token, but there's nothing saying what the token is, how to get it, why you should care, etc. The README for this repo is the best place to find that information atm, so we should try to guide a user to this repo ("Not sure what to do next? The README for this Starter Kit explains how to get started" or something like this)

On the Dashboard, we should have a button that takes the user to the repo. We will have a live demo running, so we want users to be able to easily find the repo from the live demo.

### Describe the solution you'd like

GitHub button

### Describe alternatives you've considered

_No response_

### PR DESCRIPTION
**Pull request by dmytro-tinybird**
# Description

Add link to GH in credentials modal
Add GH "Star" to header
Fix popover styles
Update codeowners

Fixes #9

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

# How Has This Been Tested?

- [ ] Manually

# Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have update the [CHANGELOG](https://github.com/tinybirdco/log-analytics-starter-kit/blob/main/CHANGELOG.md)
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sdairs** [comment]
@dmytro-tinybird Looks good; I see a TODO in there, are we resolving that before merge?

**Comment by dmytro-tinybird** [comment]
> @dmytro-tinybird Looks good; I see a TODO in there, are we resolving that before merge?

It would basically show GH stars, and I'd rather show it when we have some stars, right? 0 stars are kinda embarrassing.

**Comment by sdairs** [comment]
> > @dmytro-tinybird Looks good; I see a TODO in there, are we resolving that before merge?
> 
> It would basically show GH stars, and I'd rather show it when we have some stars, right? 0 stars is kinda embarrassing.

We have 5! 😂 Maybe just change it to a 'GitHub' button rather than a Star button?

**Comment by sdairs** [comment]
How about just a Tremor button with a Github logo SVG & "Find on GitHub" text?

**Review by sdairs — APPROVED** [review]

**Pull request merged**
